# Generated by Django 5.2.6 on 2025-09-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_alter_channelsocialaccount_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='logo',
        ),
        migrations.AddField(
            model_name='channel',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
