# Generated by Django 5.2.6 on 2025-09-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_remove_channel_logo_channel_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='socialnetwork',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='social_network_icons/'),
        ),
    ]
