# Generated by Django 5.2.6 on 2025-09-11 05:31

import apps.analytic.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelSocialStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[apps.analytic.validators.validate_year])),
                ('month', models.PositiveIntegerField(validators=[apps.analytic.validators.validate_month])),
                ('views', models.PositiveIntegerField(default=0)),
                ('followers', models.PositiveIntegerField(default=0)),
                ('content_count', models.PositiveIntegerField(default=0)),
                ('channel_social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel.channelsocialaccount')),
                ('smm_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='employee.smmstaff')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('smm_staff', 'year', 'month'), name='unique_staff_year_month')],
            },
        ),
    ]
