# Generated by Django 5.2.6 on 2025-09-12 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0001_initial'),
        ('channel', '0002_alter_channelsocialaccount_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('content', 'Content'), ('views', 'Views'), ('followers', 'Followers')], max_length=50)),
                ('min_value', models.IntegerField()),
                ('step', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.socialnetwork')),
            ],
        ),
        migrations.CreateModel(
            name='KPIThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.socialnetwork')),
            ],
        ),
    ]
