# Generated by Django 5.2.6 on 2025-09-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0002_kpiformula_kpithreshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpiformula',
            options={'ordering': ['min_value']},
        ),
        migrations.AlterModelOptions(
            name='kpithreshold',
            options={'ordering': ['-max_score']},
        ),
        migrations.RenameField(
            model_name='kpithreshold',
            old_name='ball',
            new_name='max_score',
        ),
        migrations.RenameField(
            model_name='kpithreshold',
            old_name='percentage',
            new_name='min_score',
        ),
        migrations.RemoveField(
            model_name='kpiformula',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='kpiformula',
            name='step',
        ),
        migrations.RemoveField(
            model_name='kpithreshold',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='kpithreshold',
            name='social_network',
        ),
        migrations.AddField(
            model_name='kpiformula',
            name='points',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpithreshold',
            name='percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpiformula',
            name='metric',
            field=models.CharField(choices=[('content', 'Content count'), ('views', 'Views'), ('followers', 'Followers')], max_length=30),
        ),
        migrations.AlterField(
            model_name='kpiformula',
            name='min_value',
            field=models.PositiveIntegerField(),
        ),
    ]
