# Generated by Django 5.2.6 on 2025-09-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0003_alter_kpiformula_options_alter_kpithreshold_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KPIThreshold',
        ),
    ]
