# Generated by Django 5.2.6 on 2025-09-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytic', '0004_delete_kpithreshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpiformula',
            options={'ordering': ['-min_value']},
        ),
    ]
