# Generated by Django 5.2.6 on 2025-09-13 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smmstaff',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smm_staffs', to='employee.employee'),
        ),
    ]
